
BLOCK_SIZE = 500
FINAL_TERMS_SIZE = 25000
PATH = "C:/Users/liang/zhong/new/2019FALL/6791/Lab1/reuters21578/reut2-0"

INDEX = "INDEXS/"

BLOCK_PATH = "INDEXS/DISK/"
MERGE_BLOCK_PATH = "INDEXS/MERGE_BLOCK_INDEX/"

NO_NUMBER_BLOCK_PATH = "INDEXS/NO_NUMBER_DISK/"
NO_NUMBER_MERGE_BLOCK_PATH = "INDEXS/NO_NUMBER_MERGE_BLOCK_INDEX/"

CASE_FOLDING_BLOCK_PATH = "INDEXS/CASE_FOLDING_DISK/"
CASE_FOLDING_MERGE_BLOCK_PATH = "INDEXS/CASE_FOLDING_MERGE_BLOCK_INDEX/"


STOP_WORDS_30_BLOCK_PATH = "INDEXS/STOP_WORDS_30_DISK/"
STOP_WORDS_30_MERGE_BLOCK_PATH = "INDEXS/STOP_WORDS_30_MERGE_BLOCK_INDEX/"

STOP_WORDS_150_BLOCK_PATH = "INDEXS/STOP_WORDS_150_DISK/"
STOP_WORDS_150_MERGE_BLOCK_PATH = "INDEXS/STOP_WORDS_150_MERGE_BLOCK_INDEX/"

QUERY_AND = "and"
QUERY_OR = "or"
QUERY_SINGLE = "single"

EXIT = "exit"
