
BLOCK_SIZE = 500
FINAL_TERMS_SIZE = 25000
PATH = "C:/Users/liang/zhong/new/2019FALL/6791/Lab1/reuters21578/reut2-0"

BLOCK_PATH = "BLOCK_INDEX/"
MERGE_BLOCK_PATH = "MERGE_BLOCK_INDEX/"

NO_NUMBER_BLOCK_PATH = "NO_NUMBER_BLOCK_INDEX/"
NO_NUMBER_MERGE_BLOCK_PATH = "NO_NUMBER_MERGE_BLOCK_INDEX/"

CASE_FOLDING_BLOCK_PATH = "CASE_FOLDING_BLOCK_INDEX/"
CASE_FOLDING_MERGE_BLOCK_PATH = "CASE_FOLDING_MERGE_BLOCK_INDEX/"


STOP_WORDS_30_BLOCK_PATH = "STOP_WORDS_30_BLOCK_INDEX/"
STOP_WORDS_30_MERGE_BLOCK_PATH = "STOP_WORDS_30_MERGE_BLOCK_INDEX/"

STOP_WORDS_150_BLOCK_PATH = "STOP_WORDS_150_BLOCK_INDEX/"
STOP_WORDS_150_MERGE_BLOCK_PATH = "STOP_WORDS_150_MERGE_BLOCK_INDEX/"

QUERY_AND = "and"
QUERY_OR = "or"

EXIT = "exit"
